const express = require('express');
const app = express();
const port = 3001;
const bodyParser = require("body-parser");
const swaggerJsdoc = require("swagger-jsdoc");
const swaggerUI = require("swagger-ui-express");
const cors = require("cors");
const {check, validationResult} = require('express-validator');

const options = {
  swaggerDefinition: {
    info: {
      title: 'Test Company API',
      version: '1.0.0',
      description: 'Test Company Express API with autogenerated swagger doc',
    },
	host:'137.184.59.223:3001',
	basePath: '/',
  },
  apis: ['./server.js'],
};

const specs = swaggerJsdoc(options);
app.use('/docs', swaggerUI.serve, swaggerUI.setup(specs));
app.use(cors());

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended:false}));


const mariadb = require('mariadb');
const pool = mariadb.createPool({
	host: 'localhost',
	user: 'root',
	password: 'root',
	database: 'sample',
	port: 3306,
	connectionLimit: 5
});

/**
 * @swagger
 * /agents:
 *    get:
 *      description: Returns all agents 
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: agent object
 */
app.get('/agents', async (req, res) => {

try{
const result = await pool.query("Select * from agents");
res.json(result);
}
catch(err){
throw err;
}
});

/**
 * @swagger
 * /company:
 *    get:
 *      description: Returns all details of the company
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: company objects
 */
app.get('/company', async (req,res) =>{
try{
const result = await pool.query("SELECT * FROM company");
res.json(result);
}
catch(err){
throw err;
}
});

 /**
 * @swagger
 * /customer:
 *    get:
 *      description: Returns all customer names when customer city is New York
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: customer objects
 */
app.get('/customer', async (req, res) =>{
try{
const result = await pool.query("SELECT CUST_NAME FROM customer WHERE CUST_CITY = 'New York'");
res.json(result);
}
catch(err){
throw err;
}
});

/**
 * @swagger
 * /daysorder:
 *    get:
 *      description: Returns all order numbers, amounts, advance amounts, order dates and customer code
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: days order objects
 */
app.get('/daysorder', async (req, res) =>{
try{
const result = await pool.query("SELECT ORD_NUM, ORD_AMOUNT, ADVANCE_AMOUNT, ORD_DATE, CUST_CODE from daysorder");
res.json(result);
}
catch(err){
throw err;
}
});

/**
 * @swagger
 * /foods:
 *    get:
 *      description: Returns all item from foods
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: food objects
 */
app.get('/foods', async (req, res) =>{
try{
const result = await pool.query("SELECT * FROM foods");
res.json(result);
}
catch(err){
throw err;
}
});

 /**
 * @swagger
 * /listofitem:
 *    get:
 *      description: Returns all list of items
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: list of item objects
 */
app.get('/listofitem', async (req, res) =>{
try{
const result = await pool.query("SELECT * FROM listofitem");
res.json(result);
}
catch(err){
throw err;
}});

/**
 * @swagger
 * /orders:
 *    get:
 *      description: Returns all order number, order amounts, order dates and order description from orders
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: order objects
 */
app.get('/orders', async (req, res) =>{
try{
const result = await pool.query("SELECT ORD_NUM, ORD_AMOUNT, ORD_DATE, ORD_DESCRIPTION FROM orders");
res.json(result);
}
catch(err){
throw err;
}});

/**
 * @swagger
 * /student:
 *    get:
 *      description: Returns all student names where their section is b
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: student name objects
 */
app.get('/student', async (req, res) =>{
try{
const result = await pool.query("SELECT NAME FROM student WHERE Section ='b'");
res.json(result);
}
catch(err){
throw err;
}});

 /**
 * @swagger
 * /studentreport:
 *    get:
 *      description: Returns all from student reports
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: student report objects
 */
app.get('/studentreport', async (req, res) =>{
try{
const result = await pool.query("SELECT * FROM studentreport");
res.json(result);
}
catch(err){
throw err;
}});

//make a post request (adding something new)
/**
 * @swagger
 * definitions:
 *   Food:
 *     properties:
 *       ITEM_ID:
 *         type: string
 *       ITEM_NAME:
 *         type: string
 *       ITEM_UNIT:
 *         type: string
 *       COMPANY_ID:
 *         type: string
 */
/**
 * @swagger
 * /food:
 *    post:
 *      description: Add a record to the food table
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: Added data to the food table
 *      parameters:
 *          - name: Food
 *            description: the food object
 *            in: body
 *            required: true
 *            schema:
 *              $ref: '#/definitions/Food'
 *
 */
app.post('/food',
   [ check('ITEM_ID','Item ID is required').not().isEmpty().trim(),     check('ITEM_NAME').trim(),     check('ITEM_UNIT').trim(),       check('COMPANY_ID').trim()       ]
    ,async (req,res)=>{
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).send(errors);
    }
    let conn;
    console.log(req.body)
    const {ITEM_ID,ITEM_NAME,ITEM_UNIT,COMPANY_ID}=req.body

    try{
        conn= await pool.getConnection();

        const result= await pool.query(`INSERT INTO foods (ITEM_ID, ITEM_NAME, ITEM_UNIT, COMPANY_ID) VALUES ('${ITEM_ID}', '${ITEM_NAME}', '${ITEM_UNIT}','${COMPANY_ID}')`);
        console.log(result)
      res.status(200).send('Record Inserted Successfully');
    }
catch(error) {
         console.error(error.message)
        res.status(500).send('Server Error');
    }
finally{
    if (conn) return conn.end();
}

});





//make a patch request (partially updating something existing?)
/**
 * @swagger
 * /food/{id}:
 *    patch:
 *      description: Update a record from food table
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: Updated data from food table
 *      parameters:
 *          - name: id
 *            in: path
 *            required: true
 *            type: string
 *          - name: Food
 *            description: food object
 *            in: body
 *            required: true
 *            schema:
 *              $ref: '#/definitions/Food'
 *
 */
app.patch('/food/:id',
    async (req,res)=>{
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).send(errors);
    }
    let conn;
    const id = req.params.id
    const {ITEM_NAME,ITEM_UNIT,COMPANY_ID}=req.body
    let rows=0
    try{
        conn= await pool.getConnection();
	if (ITEM_NAME && ITEM_UNIT && COMPANY_ID){
        	const result= await pool.query(`UPDATE foods SET ITEM_NAME='${ITEM_NAME}', ITEM_UNIT='${ITEM_UNIT}' , COMPANY_ID='${COMPANY_ID}' 
            WHERE ITEM_ID = '${id}'`)
		rows = result.affectedRows
	}
    else if (ITEM_NAME && ITEM_UNIT ){
        	const result= await pool.query(`UPDATE foods SET ITEM_NAME='${ITEM_NAME}', ITEM_UNIT='${ITEM_UNIT}'  
            WHERE ITEM_ID = '${id}'`)
		rows = result.affectedRows
	}
   else if (ITEM_NAME &&  COMPANY_ID){
        	const result= await pool.query(`UPDATE foods SET ITEM_NAME='${ITEM_NAME}',  COMPANY_ID='${COMPANY_ID}' 
            WHERE ITEM_ID = '${id}'`)
		rows = result.affectedRows
	}
    else if ( ITEM_UNIT && COMPANY_ID){
        	const result= await pool.query(`UPDATE foods SET ITEM_UNIT='${ITEM_UNIT}' , COMPANY_ID='${COMPANY_ID}' 
            WHERE ITEM_ID = '${id}'`)
		rows = result.affectedRows
	}
    else if (ITEM_NAME){
        	const result= await pool.query(`UPDATE foods SET ITEM_NAME='${ITEM_NAME}'
            WHERE ITEM_ID = '${id}'`)
		rows = result.affectedRows
	}
    else if ( ITEM_UNIT){
        	const result= await pool.query(`UPDATE foods SET ITEM_UNIT='${ITEM_UNIT}' 
            WHERE ITEM_ID = '${id}'`)
		rows = result.affectedRows
	}
    else if (COMPANY_ID){
        	const result= await pool.query(`UPDATE foods SET COMPANY_ID='${COMPANY_ID}' 
            WHERE ITEM_ID = '${id}'`)
		rows = result.affectedRows
	}

	
	if(rows==0) {
        	return res.status(404).send('Record not Found');
        }
	return res.status(200).send("Updated Successfully");
	}
catch(error) {
	res.status(500).send('Server Error');
    }
finally{
    if (conn) return conn.end();
}
});





//make a put request (updating something existing)
/**
 * @swagger
 * /food/{id}:
 *    put:
 *      description: update record in food table, create new if not one to edit
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: Added data to company table
 *      parameters:
 *          - name: id
 *            in: path
 *            required: true
 *            type: string
 *          - name: Food
 *            description: food object
 *            in: body
 *            required: true
 *            schema:
 *              $ref: '#/definitions/Food'
 *
 */


 app.put('/food/:id', 
	[ check('ITEM_NAME').not().isEmpty().trim(),
		  check('ITEM_UNIT').not().isEmpty().trim(),
      check('COMPANY_ID').not().isEmpty().trim()
      ],
	async (req,res)=>{
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).send(errors);
    }
    let conn;
    const id = req.params.id   
    console.log(req.params.id)
    const {ITEM_NAME,ITEM_UNIT,COMPANY_ID}=req.body
 
    try{
        conn= await pool.getConnection();
	const result= await pool.query(`UPDATE foods SET ITEM_NAME='${ITEM_NAME}', ITEM_UNIT='${ITEM_UNIT}', COMPANY_ID='${COMPANY_ID}' WHERE ITEM_ID = '${id}'`)
	if (result.affectedRows==0){
	    const result= await pool.query(`INSERT INTO foods (ITEM_ID, ITEM_NAME, ITEM_UNIT,COMPANY_ID) VALUES ('${id}', '${ITEM_NAME}', '${ITEM_UNIT}', '${COMPANY_ID}')`)
	}
    res.status(200).send('Record Updated Successfully');
}
catch(error) {
         console.error(error.message)
        res.status(500).send('Server Error');
    }
finally{
    if (conn) return conn.end();
}

});
 
//make a delete request
/**
 * @swagger
 * /food/{id}:
 *    delete:
 *      description: Delete the record in the food table
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: Successfully deleted record from table
 *      parameters:
 *          - name: id
 *            in: path
 *            required: true
 *            type: string
 *
 */
app.delete('/food/:id', async (req,res)=>{
    let conn;
    const id = req.params.id
    try{
        conn= await pool.getConnection();
	const result= await pool.query(`DELETE FROM foods WHERE ITEM_ID='${id}'`);
	if(result.affectedRows==0) {
		return res.status(404).send('Record not Found');
	}
	return res.status(404).send('Deleted Record Successfully!');
	}
   catch(error) {
         console.error(error.message)
        res.status(500).send('Server Error');
    }
finally{
    if (conn) return conn.end();
}
});

//make a post request (adding something new)
/**
 * @swagger
 * definitions:
 *   Company:
 *     properties:
 *       COMPANY_ID:
 *         type: string
 *       COMPANY_NAME:
 *         type: string
 *       COMPANY_CITY:
 *         type: string
 */
/**
 * @swagger
 * /company:
 *    post:
 *      description: Add a record to the company table
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: Added data to the company table
 *      parameters:
 *          - name: Company
 *            description: the company object
 *            in: body
 *            required: true
 *            schema:
 *              $ref: '#/definitions/Company'
 *
 */
 app.post('/company',
 [ check('COMPANY_ID','company ID is required').not().isEmpty().trim(),     check('COMPANY_NAME').trim(),     check('COMPANY_CITY').trim()       ]
  ,async (req,res)=>{
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).send(errors);
  }
  let conn;
  console.log(req.body)
  const {COMPANY_ID,COMPANY_NAME,COMPANY_CITY}=req.body

  try{
      conn= await pool.getConnection();

      const result= await pool.query(`INSERT INTO company(COMPANY_ID, COMPANY_NAME, COMPANY_CITY) VALUES ('${COMPANY_ID}', '${COMPANY_NAME}', '${COMPANY_CITY}')`);
      console.log(result)
    res.status(200).send('Record Inserted Successfully');
  }
catch(error) {
       console.error(error.message)
      res.status(500).send('Server Error');
  }
finally{
  if (conn) return conn.end();
}

});





//make a patch request (partially updating something existing?)
/**
* @swagger
* /company/{id}:
*    patch:
*      description: Update a record from company table
*      produces:
*          - application/json
*      responses:
*          200:
*              description: Updated data from company table
*      parameters:
*          - name: id
*            in: path
*            required: true
*            type: string
*          - name: Company
*            description: company object
*            in: body
*            required: true
*            schema:
*              $ref: '#/definitions/Company'
*
*/
app.patch('/company/:id',
  async (req,res)=>{
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).send(errors);
  }
  let conn;
  const id = req.params.id
  const {COMPANY_NAME,COMPANY_CITY}=req.body
  let rows=0
  try{
      conn= await pool.getConnection();
  if (COMPANY_NAME && COMPANY_CITY){
          const result= await pool.query(`UPDATE company SET COMPANY_NAME='${COMPANY_NAME}', COMPANY_CITY='${COMPANY_CITY}'
          WHERE COMPANY_ID = '${id}'`)
      rows = result.affectedRows
  }
  else if (COMPANY_NAME){
          const result= await pool.query(`UPDATE company SET COMPANY_NAME='${COMPANY_NAME}'
          WHERE COMPANY_ID = '${id}'`)
      rows = result.affectedRows
  }
  else if (COMPANY_CITY){
          const result= await pool.query(`UPDATE company SET COMPANY_CITY='${COMPANY_CITY}' 
          WHERE COMPANY_ID = '${id}'`)
      rows = result.affectedRows
  }

  
  if(rows==0) {
          return res.status(404).send('Record not Found');
      }
  return res.status(200).send("Updated Successfully");
  }
catch(error) {
  res.status(500).send('Server Error');
  }
finally{
  if (conn) return conn.end();
}
});





//make a put request (updating something existing)
/**
* @swagger
* /company/{id}:
*    put:
*      description: update record in company table, create new if not one to edit
*      produces:
*          - application/json
*      responses:
*          200:
*              description: Added data to company table
*      parameters:
*          - name: id
*            in: path
*            required: true
*            type: string
*          - name: Company
*            description: company object
*            in: body
*            required: true
*            schema:
*              $ref: '#/definitions/Company'
*
*/


app.put('/company/:id', 
  [ check('COMPANY_NAME').not().isEmpty().trim(),
        check('COMPANY_CITY').not().isEmpty().trim()
    ],
  async (req,res)=>{
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).send(errors);
  }
  let conn;
  const id = req.params.id   
  console.log(req.params.id)
  const {COMPANY_NAME,COMPANY_CITY}=req.body

  try{
      conn= await pool.getConnection();
  const result= await pool.query(`UPDATE company SET COMPANY_NAME='${COMPANY_NAME}', COMPANY_CITY='${COMPANY_CITY}' WHERE COMPANY_ID = '${id}'`)
  if (result.affectedRows==0){
      const result= await pool.query(`INSERT INTO company (COMPANY_ID, COMPANY_NAME, COMPANY_CITY) VALUES ('${id}', '${COMPANY_NAME}', '${COMPANY_CITY}'`)
  }
  res.status(200).send('Record Updated Successfully');
}
catch(error) {
       console.error(error.message)
      res.status(500).send('Server Error');
  }
finally{
  if (conn) return conn.end();
}

});

//make a delete request
/**
* @swagger
* /company/{id}:
*    delete:
*      description: Delete the record in the company table
*      produces:
*          - application/json
*      responses:
*          200:
*              description: Successfully deleted record from table
*      parameters:
*          - name: id
*            in: path
*            required: true
*            type: string
*
*/
app.delete('/company/:id', async (req,res)=>{
  let conn;
  const id = req.params.id
  try{
      conn= await pool.getConnection();
  const result= await pool.query(`DELETE FROM company WHERE COMPANY_ID='${id}'`);
  if(result.affectedRows==0) {
      return res.status(404).send('Record not Found');
  }
  return res.status(404).send('Deleted Record Successfully!');
  }
 catch(error) {
       console.error(error.message)
      res.status(500).send('Server Error');
  }
finally{
  if (conn) return conn.end();
}
});


app.listen(port, () => {
console.log(`Example app listening at http://localhost:${port}`)
});
